name = "spoke_mqtt_js"
version = "1.0.0"
target = "javascript"

description = "A Gleam MQTT 3.1.1 client for the JavaScript runtime."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "spoke", path = "spoke_mqtt_js" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
drift = ">= 1.0.0 and < 2.0.0"
drift_js = ">= 1.0.1 and < 2.0.0"
spoke_core = { path = "../spoke_core" }
spoke_mqtt = { path = "../spoke_mqtt" }
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
exemplify = { path = "../dev/exemplify" }
