name = "spoke_mqtt_js"
version = "1.0.1"
target = "javascript"

description = "A Gleam MQTT 3.1.1 client for the JavaScript runtime."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "spoke", path = "spoke_mqtt_js", tag-prefix = "spoke_mqtt_js-" }

[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
drift = ">= 1.0.0 and < 2.0.0"
drift_js = ">= 1.0.1 and < 2.0.0"
spoke_core = ">= 1.0.0 and < 2.0.0"
spoke_mqtt = ">= 1.0.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
checkmark = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
