name = "spoke_packet"
version = "1.0.0"

description = "Encode and decode MQTT 3.1.1 packets to/from binary data."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "spoke", path = "spoke_packet", tag-prefix = "spoke_packet-" }
internal_modules = ["spoke/packet/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.0 and < 2.0.0"
exemplify = { path = "../dev/exemplify" }
