name = "spoke_core"
version = "1.0.0"

description = "Purely functional core logic for an MQTT 3.1.1 client, using drift."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "spoke", path = "spoke_core", tag-prefix = "spoke_core-" }
internal_modules = ["spoke/core/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
spoke_packet = ">= 1.0.0 and < 2.0.0"
spoke_mqtt = { path = "../spoke_mqtt" }
drift = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
drift_record = ">= 1.0.0 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
